[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "cloak"
version = "0.2.0"
description = "A steganography CLI tool that hides encrypted messages in images"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Lovaszy Leonard", email = "leonardlovaszy@gmail.com"}
]
dependencies = [
    "Pillow",
    "rich",
    "questionary",
    "pyfiglet",
    "cryptography",
]

[project.scripts]
cloak = "stego.__main__:main"

[tool.setuptools.packages.find]
where = ["."]